[package]
name = "mas-jose"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.53"
async-trait = "0.1.52"
base64ct = { version = "1.0.1", features = ["std"] }
chrono = { version = "0.4.19", features = ["serde"] }
crypto-mac = { version = "0.11.1", features = ["std"] }
digest = "0.10.3"
ecdsa = { version = "0.13.4", features = ["sign", "verify", "pem", "pkcs8"] }
elliptic-curve = { version = "0.11.12", features = ["ecdh", "pem"] }
futures-util = "0.3.21"
hmac = "0.12.1"
http = "0.2.6"
p256 = { version = "0.10.1", features = ["ecdsa", "pem", "pkcs8"] }
pkcs1 = { version = "0.3.3", features = ["pem", "pkcs8"] }
pkcs8 = { version = "0.8.0", features = ["pem"] }
rand = "0.8.5"
rsa = { git = "https://github.com/RustCrypto/RSA.git" }
schemars = "0.8.8"
sec1 = "0.2.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_with = { version = "1.12.0", features = ["base64"] }
sha2 = "0.10.2"
signature = "1.4.0"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["macros", "rt", "sync"] }
tower = "0.4.12"
url = { version = "2.2.2", features = ["serde"] }

mas-iana = { path = "../iana" }

[dev-dependencies]
mas-http = { path = "../http" }
