[package]
name = "mas-jose"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.65"
base64ct = { version = "1.5.2", features = ["std"] }
chrono = { version = "0.4.22", features = ["serde"] }
digest = "0.10.5"
ecdsa = { version = "0.14.7", features = ["sign", "verify"] }
elliptic-curve = "0.12.3"
generic-array = "0.14.6"
hmac = "0.12.1"
k256 = { version = "0.11.5", features = ["ecdsa"] }
p256 = { version = "0.11.1", features = ["ecdsa"] }
p384 = { version = "0.11.2", features = ["ecdsa"] }
rand = "0.8.5"
rsa = "0.7.0-rc.0"
schemars = "0.8.10"
sec1 = "0.3.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
serde_with = { version = "2.0.1", features = ["base64"] }
sha2 = { version = "0.10.6", features = ["oid"] }
signature = "1.6.3"
thiserror = "1.0.36"
tracing = "0.1.36"
url = { version = "2.3.1", features = ["serde"] }

mas-iana = { path = "../iana" }
