[package]
name = "mas-matrix-synapse"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.72"
async-trait = "0.1.72"
http = "0.2.9"
serde = { version = "1.0.177", features = ["derive"] }
tower = { version = "0.4.13", features = ["util"] }
tracing = "0.1.37"
url = "2.4.0"

mas-axum-utils = { path = "../axum-utils" }
mas-http = { path = "../http" }
mas-matrix = { path = "../matrix" }
