[package]
name = "mas-axum-utils"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
async-trait = "0.1.53"
axum = { version = "0.5.1", features = ["headers"] }
bincode = "1.3.3"
chrono = "0.4.19"
cookie = { version = "0.16.0", features = ["signed", "private", "percent-encode"] }
data-encoding = "2.3.2"
futures-util = "0.3.21"
headers = "0.3.7"
http = "0.2.6"
mime = "0.3.16"
rand = "0.8.5"
serde = "1.0.136"
serde_with = "1.12.0"
serde_urlencoded = "0.7.1"
serde_json = "1.0.79"
sqlx = "0.5.11"
thiserror = "1.0.30"
tokio = "1.17.0"
tracing = "0.1.32"
url = "2.2.2"

# TODO: remove the config dependency by moving out the encrypter
mas-config = { path = "../config" }
mas-templates = { path = "../templates" }
mas-storage = { path = "../storage" }
mas-data-model = { path = "../data-model" }
mas-jose = { path = "../jose" }
mas-iana = { path = "../iana" }

[features]
