[package]
name = "mas-axum-utils"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
async-trait = "0.1.59"
axum = { version = "0.6.1", features = ["headers"] }
axum-extra = { version = "0.4.2", features = ["cookie-private"] }
chrono = "0.4.23"
data-encoding = "2.3.3"
futures-util = "0.3.25"
headers = "0.3.8"
http = "0.2.8"
http-body = "0.4.5"
mime = "0.3.16"
rand = "0.8.5"
serde = "1.0.149"
serde_with = "2.1.0"
serde_urlencoded = "0.7.1"
serde_json = "1.0.89"
sqlx = "0.6.2"
thiserror = "1.0.37"
tokio = "1.23.0"
tower = { version = "0.4.13", features = ["util"] }
tracing = "0.1.37"
url = "2.3.1"
ulid = { version = "1.0.0", features = ["serde"] }

mas-data-model = { path = "../data-model" }
mas-http = { path = "../http", features = ["client"] }
mas-iana = { path = "../iana" }
mas-jose = { path = "../jose" }
mas-keystore = { path = "../keystore" }
mas-storage = { path = "../storage" }
mas-templates = { path = "../templates" }

[features]
native-roots = ["mas-http/native-roots"]
webpki-roots = ["mas-http/webpki-roots"]
