[package]
name = "oauth2-types"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
http = "0.2.6"
serde = "1.0.133"
serde_json = "1.0.74"
language-tags = { version = "0.3.2", features = ["serde"] }
url = { version = "2.2.2", features = ["serde"] }
parse-display = "0.5.3"
indoc = "1.0.3"
serde_with = { version = "1.11.0", features = ["chrono"] }
chrono = "0.4.19"
sha2 = "0.10.0"
data-encoding = "2.3.2"
thiserror = "1.0.30"
itertools = "0.10.3"
