[package]
name = "oauth2-types"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
http = "0.2.7"
serde = "1.0.137"
serde_json = "1.0.81"
language-tags = { version = "0.3.2", features = ["serde"] }
url = { version = "2.2.2", features = ["serde"] }
parse-display = "0.5.5"
indoc = "1.0.5"
serde_with = { version = "1.13.0", features = ["chrono"] }
chrono = "0.4.19"
sha2 = "0.10.2"
data-encoding = "2.3.2"
thiserror = "1.0.31"
itertools = "0.10.3"

mas-iana = { path = "../iana" }
mas-jose = { path = "../jose" }
