[package]
name = "mas-tower"
description = "Tower layers used by the Matrix Authentication Service"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
http.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
tower = "0.4.13"
tokio = { version = "1.35.1", features = ["time"] }
opentelemetry.workspace = true
opentelemetry-http = "0.10.0"
opentelemetry-semantic-conventions.workspace = true
pin-project-lite = "0.2.13"
