[package]
name = "mas-templates"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
tracing = "0.1.37"
tokio = { version = "1.23.0", features = ["macros", "rt"] }

anyhow = "1.0.66"
thiserror = "1.0.37"

tera = "1.17.1"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
serde_urlencoded = "0.7.1"

camino = "1.1.1"
chrono = "0.4.23"
url = "2.3.1"
http = "0.2.8"
ulid = { version = "1.0.0", features = ["serde"] }
rand = "0.8.5"

oauth2-types = { path = "../oauth2-types" }
mas-data-model = { path = "../data-model" }
mas-router = { path = "../router" }
