[package]
name = "mas-templates"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[features]
dev = []

[dependencies]
tracing = "0.1.36"
tokio = { version = "1.20.1", features = ["macros"] }

anyhow = "1.0.59"
thiserror = "1.0.31"

tera = "1.16.0"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
serde_urlencoded = "0.7.1"

chrono = "0.4.19"
url = "2.2.2"

oauth2-types = { path = "../oauth2-types" }
mas-data-model = { path = "../data-model" }
mas-config = { path = "../config" }
mas-router = { path = "../router" }
