[package]
name = "mas-templates"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
tracing = "0.1.37"
tokio = { version = "1.26.0", features = ["macros", "rt"] }

anyhow = "1.0.69"
thiserror = "1.0.39"

tera = "1.18.0"
serde = { version = "1.0.155", features = ["derive"] }
serde_json = "1.0.94"
serde_urlencoded = "0.7.1"

camino = "1.1.4"
chrono = "0.4.24"
url = "2.3.1"
http = "0.2.9"
ulid = { version = "1.0.0", features = ["serde"] }
rand = "0.8.5"

oauth2-types = { path = "../oauth2-types" }
mas-data-model = { path = "../data-model" }
mas-router = { path = "../router" }
