[package]
name = "mas-tasks"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
tokio = "1.23.0"
async-trait = "0.1.60"
tokio-stream = "0.1.11"
futures-util = "0.3.25"
tracing = "0.1.37"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "postgres"] }

mas-storage = { path = "../storage" }
mas-storage-pg = { path = "../storage-pg" }
